version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_ROOT_PASSWORD: password
      POSTGRES_DATABASE: root
    ports:
      - "3307:3307"

  web:
    build: .
    #this sentence mean to abriviation of "rails server"
    command: rails s -p 3001 -b '0.0.0.0'
    volumes:
      - .:/app_name
    ports:
      - "3001:3001"
    links:
      - db